using System;
using System.Collections.Generic;
using System.Linq;
using FileHelpers;
using GenLib.Helper;

namespace AstroLib.ObjectLibrary.SAC
{
    public class Loader<T> where T : Record
    {
        public Loader() : this(new FileHelperEngine<T>(), new Constellations(), new Catalogs())
        {
        }

        public Loader(FileHelperEngine<T> engine, Constellations constellations, Catalogs catalogs)
        {
            Engine = engine;
            Constellations = constellations;
            Catalogs = catalogs;
        }

        private FileHelperEngine<T> Engine { get; set; }
        private Constellations Constellations { get; set; }
        private Catalogs Catalogs { get; set; }

        public List<T> Load(string filename)
        {
            var st = new StringTokenizer();

            Engine.AfterReadRecord
                += (_, e) =>
                       {
                           st.Tokenize(e.Record.RA);
                           e.Record.RA = st.NextToken() + ":" + st.NextToken();
                           st.Tokenize(e.Record.DEC);
                           e.Record.DEC = st.NextToken() + ":" + st.NextToken();

                           string constellation;
                           if (Constellations.Lookup.TryGetValue(e.Record.CON, out constellation))
                               e.Record.CON = constellation;

//                           if (st.Tokenize(e.Record.OBJECT))
//                               st.Tokens.ForEach(t => NoteCatalogDuplicates(t, e.RecordLine));
//                           if (st.Tokenize(e.Record.OTHER, " ;".ToCharArray()))
//                               st.Tokens.ForEach(t => NoteCatalogDuplicates(t, e.RecordLine));
//
//                           TestForMissingCatalog(e.Record.OBJECT, e.RecordLine);
//                           TestForMissingCatalog(e.Record.OTHER, e.RecordLine);
                       };

            return Engine.ReadFile(filename).ToList();
        }

        private void TestForMissingCatalog(string name, string record)
        {
            if (name.Length > 0)
                Catalogs.CatalogFound(name);
            else
                Console.WriteLine(@"no catalog for " + name + @" found in " + record);
        }

        private static void NoteCatalogDuplicates(string token, string record)
        {
            if (token.IndexOf("SL") > -1)
                Console.WriteLine(@"possible duplicate catalog of \""SL\"" found in " + record);
        }
    }
}

// output:

// possible duplicate catalog of \"SL\" found in "SL 42            ","                  ","DRKNB","CRA","19 10.3","-37 08","79.9","79.9","379","22","  12   m","   8   m","   ","6 E        ","    ","     ","    ","                                                       ","1.8 degrees following bright nebulae NGC 6726-7                                       "
// possible duplicate catalog of \"SL\" found in "SL 11            ","                  ","DRKNB","LUP","15 57.0","-37 48","79.9","79.9","374","21"," 150   m","  40   m","   ","6 Ir       ","    ","     ","    ","                                                       ","Elongated E and W                                                                     "
// possible duplicate catalog of \"SL\" found in "SL  7            ","                  ","DRKNB","LUP","16 01.8","-41 52","79.9","79.9","406","22","  60   m","  10   m","   ","6 Ir       ","    ","     ","    ","                                                       ","Several overlapping clouds                                                            "
// possible duplicate catalog of \"SL\" found in "SL  8            ","                  ","DRKNB","NOR","16 14.2","-44 04","79.9","79.9","406","22","  25   m","   5   m","   ","6 Ir       ","    ","     ","    ","                                                       ","Curved                                                                                "
// possible duplicate catalog of \"SL\" found in "B 231            ","SL 24             ","DRKNB","SCO","16 37.5","-35 12","79.9","79.9","375","22","  50   m","  40   m","   ","6 Ir       ","    ","     ","    ","                                                       ","Dusky                                                                                 "
// possible duplicate catalog of \"SL\" found in "B 233            ","SL 25             ","DRKNB","SCO","16 44.1","-35 21","79.9","79.9","375","22","  55   m","  20   m","   ","5 Ir       ","    ","     ","    ","                                                       ","1 deg following B231                                                                  "
// possible duplicate catalog of \"SL\" found in "B  44a           ","SL 18             ","DRKNB","SCO","16 44.8","-40 23","79.9","79.9","407","22","   5   m","        ","   ","5 Ir       ","    ","     ","    ","                                                       ","2.4 degrees preceding bright nebula IC 4628                                           "
// possible duplicate catalog of \"SL\" found in "B 235            ","SL 15             ","DRKNB","SCO","16 46.6","-44 30","79.9","79.9","407","22","   7   m","   3   m","   ","6 E        ","    ","     ","    ","                                                       ","Elongated NE and SW;Darkest at SW end                                                 "
// possible duplicate catalog of \"SL\" found in "SL 17            ","                  ","DRKNB","SCO","16 53.0","-43 35","79.9","79.9","407","22","  15   m","   7   m","   ","5 Ir       ","    ","     ","    ","                                                       ","Near emission nebula Gum 55                                                           "
// possible duplicate catalog of \"SL\" found in "B  48            ","SL 20             ","DRKNB","SCO","17 01.0","-40 47","79.9","79.9","407","22","  40   m","  15   m","   ","5 Ir       ","    ","     ","    ","4''-medium contrast; UHC brings out BRTNB              ","1 deg south following bright nebula IC 4628                                           "
// possible duplicate catalog of \"SL\" found in "B  50            ","SL 30             ","DRKNB","SCO","17 03.0","-34 24","79.9","79.9","376","22","  15   m","        ","   ","6 Ir       ","    ","     ","    ","                                                       ","30' south preceding star CoD -33 degrees 11706                                        "
// possible duplicate catalog of \"SL\" found in "B  53            ","SL 32             ","DRKNB","SCO","17 06.1","-33 15","79.9","79.9","376","22","  30   m","  10   m","   ","4 Ir       ","    ","     ","    ","                                                       ","Curved                                                                                "
// possible duplicate catalog of \"SL\" found in "B  58            ","SL 23             ","DRKNB","SCO","17 11.2","-40 25","79.9","79.9","407","22","  30   m","  30   m","   ","6 Ir       ","    ","     ","    ","                                                       ","2.7 deg following bright nebula IC 4628; darker core at NE side                       "
// possible duplicate catalog of \"SL\" found in "B 263            ","SL 22             ","DRKNB","SCO","17 26.3","-42 38","79.9","79.9","408","22","  30   m","  30   m","   ","5 Ir       ","    ","     ","    ","                                                       ","Very slightly elongated                                                               "
// possible duplicate catalog of \"SL\" found in "SL 26            ","                  ","DRKNB","SCO","17 34.2","-40 25","79.9","79.9","408","22","  10   m","   5   m","   ","5 E        ","    ","     ","    ","                                                       ","Has fainter extensions                                                                "
// possible duplicate catalog of \"SL\" found in "SL 28            ","                  ","DRKNB","SCO","17 35.3","-39 14","79.9","79.9","408","22","  30   m","  15   m","   ","5 Ir       ","    ","     ","    ","                                                       ","Not listed in U2000 second edition                                                    "
// possible duplicate catalog of \"SL\" found in "SL  4            ","                  ","DRKNB","VEL","08 53.6","-42 13","79.9","79.9","397","20","  60   m","  10   m","   ","5 Ir       ","    ","     ","    ","                                                       ","In emission nebula Gum 17                                                             "

// no catalog for AND III found in "AND III          ","PGC 2121          ","GALXY","AND","00 35.4","+36 31","15.0","99.9","90 ","4 ","   2.0 m","   2.0 m","   ","dE2        ","    ","     ","    ","                                                       ","Andromeda Dwarf;Member Local Group                                                    "
// no catalog for AND I found in "AND I            ","PGC 2666          ","GALXY","AND","00 45.7","+38 03","13.2","99.9","90 ","4 ","   4.0 m","   3.0 m","156","E3         ","    ","     ","    ","                                                       ","Andromeda Dwarf;Member Local Group                                                    "
// no catalog for Av-Hunter 1 found in "Av-Hunter 1      ","                  ","OPNCL","AND","23 37.8","+48 34","99.9","99.9","59 ","9 ","  47   m","        ","   ","IV 2pn:b   ","16  "," 8.6 ","    ","                                                       ","Includes variable star BM And                                                         "
// no catalog for AP 2-1 found in "PK  35- 0.1      ","AP 2-1            ","BRTNB","AQL","18 58.1","+01 37","16.7","99.9","251","16","  33.0 s","        ","   ","           ","    ","15.1 ","    ","                                                       ","Not a PLNNB;compact H II region                                                       "
// no catalog for Nassau 2 found in "PK  26-11.1      ","Nassau 2          ","PLNNB","AQL","19 18.7","-11 06","13.3","99.9","296","16","  16.0 s","        ","   ","           ","    ","14   ","    ","                                                       ","                                                                                      "
// no catalog for IRAS20251-0314 found in "NGC 6915         ","IRAS20251-0314    ","GALXY","AQL","20 27.8","-03 05","13.1","99.9","253","16","   1.5 m","   0.9 m","80 ","Sab        ","    ","     ","    ","pB;S;R                                                 ","                                                                                      "
// no catalog for Aquarius Dwarf found in "MCG -02-53-003   ","Aquarius Dwarf    ","GALXY","AQR","20 46.8","-12 51","13.9","14.8","299","16","   2.2 m","   1.1 m","   ","IBm        ","    ","     ","    ","11''-eF; S; E 1.8X1; vlBM at 125X                      ","Member of Local Group                                                                 "
// no catalog for Cannon 1-4 found in "PK 342- 6.1      ","Cannon 1-4        ","PLNNB","ARA","17 27.9","-46 56","12.9","8.5 ","408","22","  10   s","        ","   ","           ","    ","16.2 ","    ","                                                       ","                                                                                      "
// no catalog for Latysev 1 found in "Latysev 1        ","                  ","OPNCL","ARI","02 53.2","+27 28","99.9","99.9","130","4 "," 330   m","        ","   ","           ","5   "," 6.7 ","    ","                                                       ","                                                                                      "
// no catalog for CRL 618 found in "PK 166- 6.1      ","CRL 618           ","PLNNB","AUR","04 42.9","+36 07","17.9","14.5","96 ","5 ","  12   s","        ","   ","           ","    ","17   ","    ","                                                       ","                                                                                      "
// no catalog for 0538+498 found in "3C 147           ","0538+498          ","QUASR","AUR","05 42.6","+49 51","17.8","99.9","66 ","5 ","        ","        ","   ","           ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for SH2-208 found in "PK 151+ 2.1      ","SH2-208           ","BRTNB","CAM","04 19.8","+53 06","99.9","99.9","39 ","1 ","   4.0 m","        ","   ","E          ","    ","13.9 ","    ","                                                       ","Not a PLNNB;H II region Sh 2-207                                                      "
// no catalog for Graham 1 found in "Graham 1         ","                  ","OPNCL","CAR","10 56.5","-63 01","99.9","99.9","449","25","   5   m","        ","   ","I 2pn:b    ","20  ","     ","    ","                                                       ","                                                                                      "
// no catalog for 50 CAS found in "NGC  771         ","50 CAS            ","1STAR","CAS","02 03.4","+72 25"," 4.0","99.9","17 ","1 ","        ","        ","   ","           ","    ","     ","    ","suspected neb *                                        ","                                                                                      "
// no catalog for SG  1  4 found in "NGC  896         ","SG  1  4          ","BRTNB","CAS","02 25.5","+62 01","99.9","99.9","17 ","1 ","  27   m","  13   m","   ","E          ","    ","     ","    ","eF;pL;iF                                               ","H III 695                                                                             "
// no catalog for Omega Centauri found in "NGC 5139         ","Omega Centauri    ","GLOCL","CEN","13 26.8","-47 29"," 3.9","99.9","403","21","  36.3 m","        ","   ","VIII       ","    ","11.5 ","BC  ","!!!eL;B;eRi;vvC                                        ","Stars mags 11...;finest globular;magnificent object                                   "
// no catalog for Circinus Dwarf found in "ESO 097-G013     ","Circinus Dwarf    ","GALXY","CIR","14 13.2","-65 20","10.6","13.8","452","25","   3.2 m","   1.2 m","40 ","Sb         ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for Auner 1 found in "Auner 1          ","                  ","OPNCL","CMA","07 04.3","-19 45","99.9","99.9","318","12","   2.5 m","        ","   ","III 2m :b  ","30  ","     ","    ","                                                       ","                                                                                      "
// no catalog for VY CMA found in "VY CMA           ","                  ","BRTNB","CMA","07 23.0","-25 46","10.8","99.9","319","19","   0.3 m","   0.2 m","   ","R          ","    "," 7.5 ","    ","                                                       ","Discovered w/ 7''                                                                     "
// no catalog for Coma I found in "Abell 1656       ","Coma I            ","GALCL","COM","12 59.8","+27 59","13.5","99.9","149","7 "," 224   m","        ","   ","2 1 II     ","    ","     ","    ","                                                       ","Dense GALCL for amateurs;72 brighter than 15 mag in 2 deg; 106 galaxies               "
// no catalog for Coalsack found in "Coalsack         ","                  ","DRKNB","CRU","12 53.0","-63 00","79.9","79.9","451","25"," 400   m"," 300   m","   ","3? Ir      ","    ","     ","    ","                                                       ","Adjacent to Southern Cross; Auke Slotegraaf gives other name as Black Magellanic Cloud"
// no catalog for PNG 75.6+4.3 found in "PK  75+ 4.1      ","PNG 75.6+4.3      ","PLNNB","CYG","20 04.4","+39 35","16.0","99.9","84 ","9 ","  30   s","  27   s","   ","3b         ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for SG  3.202 found in "NGC 6974         ","SG  3.202         ","SNREM","CYG","20 51.1","+31 50","99.9","99.9","120","9 ","        ","        ","   ","           ","    ","     ","    ","neb *;neby cE pf                                       ","                                                                                      "
// no catalog for Le Gentil 3 found in "Le Gentil 3      ","                  ","DRKNB","CYG","21 00.0","+51 00","79.9","79.9","85 ","9 "," 720   m"," 360   m","   ","           ","    ","     ","    ","naked eye at dark site; 8X42 binocs great view         ","Very large dark oval between NGC 7000 and IC 1396                                     "
// no catalog for Lg Magellanic Cl found in "Lg Magellanic Cl ","ESO 056-G115      ","GALXY","DOR","05 23.6","-69 45"," 0.4","14.1","444","24"," 550   m"," 170   m","170","SBm        ","    ","     ","    ","eB;eeL;mBM;mE;rrr                                      ","Local Group Memb;Many Cl+NB invl;SN 1987A                                             "
// no catalog for 1100+772 found in "3C 249.1         ","1100+772          ","QUASR","DRA","11 04.2","+76 59","15.7","99.9","8  ","2 ","        ","        ","   ","           ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for IRAS11294+7439 found in "NGC 3747         ","IRAS11294+7439    ","GALXY","DRA","11 32.5","+74 23","15.8","99.9","9  ","2 ","   0.7 m","   0.3 m","100","S pec      ","    ","     ","    ","eF;S;place doubtful                                    ","H III 969                                                                             "
// no catalog for Draco Dwarf found in "UGC 10822        ","Draco Dwarf       ","GALXY","DRA","17 20.2","+57 55"," 9.9","17.2","52 ","3 ","  33.5 m","  18.9 m","   ","dE3        ","    ","     ","    ","13''-vF; vL; pmE at 60X; low surf brightness           ","Member of Local Group;dwarf elliptical                                                "
// no catalog for IRAS03324-1000 found in "NGC 1363         ","IRAS03324-1000    ","GALXY","ERI","03 34.8","-09 51","13.9","99.9","267","11","   0.9 m","   0.7 m","45 ","Sbc        ","    ","     ","    ","vF;S;R;*7 sp 3.5';sp of 2                              ","                                                                                      "
// no catalog for Eridanus Cluster found in "Eridanus Cluster ","                  ","GLOCL","ERI","04 24.8","-21 11","14.7","99.9","313","19","   1   m","        ","   ","           ","    ","17.6 ","    ","                                                       ","                                                                                      "
// no catalog for DRCG 10-7 found in "NGC 1623         ","DRCG 10-7         ","GALXY","ERI","04 35.5","-13 33","16.9","99.9","269","11","   0.8 m","   0.5 m","15 ","SBO-a      ","    ","     ","    ","eF;vS;R;gbMN                                           ","                                                                                      "
// no catalog for Fornax Dwarf found in "MCG -06-07-001   ","Fornax Dwarf      ","GALXY","FOR","02 39.9","-34 32"," 8.9","13.9","354","18","  17   m","  12   m","   ","E4         ","    ","     ","    ","6''-eF; vL; R; Low Surface Brightness at 25X           ","Invl GLOCL NGC 1049;Memb Local Grp;Brightest * = 19mag                                "
// no catalog for 1641+399 found in "3C 345           ","1641+399          ","QUASR","HER","16 43.0","+39 49","16.0","99.9","114","8 ","        ","        ","   ","           ","    ","     ","    ","                                                       ","At edge of NGC 6212                                                                   "
// no catalog for Zwicky's triplet found in "Arp 103          ","Zwicky's triplet  ","GALXY","HER","16 49.5","+45 28","15.2","99.9","80 ","8 ","   0.9 m","   0.8 m","83 ","Sa         ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for Leo III found in "UGC  5364        ","Leo III           ","GALXY","LEO","09 59.4","+30 45","12.6","15.4","104","6 ","   4.9 m","   3.2 m","   ","Ir+        ","    ","     ","    ","                                                       ","Local Group dwarf irregular                                                           "
// no catalog for Leo I found in "UGC  5470        ","Leo I             ","GALXY","LEO","10 08.4","+12 18","10.2","14.8","189","13","  10.7 m","   8.3 m","80 ","dE3        ","    ","     ","    ","                                                       ","dwarf elliptical in Local Group;0.3' N of Regulus                                     "
// no catalog for Leo II found in "UGC  6253        ","Leo II            ","GALXY","LEO","11 13.5","+22 10","12.0","17.3","146","6 ","  12   m","  11   m","   ","dE0        ","    ","     ","    ","                                                       ","Memb Local Group;Dwarf elliptical                                                     "
// no catalog for F703 found in "NGC 5892         ","F703              ","GALXY","LIB","15 13.8","-15 28","11.7","14  ","289","14","   3.6 m","   2.9 m","105","SBcd       ","    ","     ","    ","eF;L;gbM                                               ","MCG - 2-39-7;Same position as Fath 703 in Burnham's F;S;R;bM 12.8m 2'                 "
// no catalog for PNG 164.8+31.1 found in "PK 164+31.1      ","PNG 164.8+31.1    ","PLNNB","LYN","07 57.8","+53 25","14.0","99.9","43 ","1 ","   6.3 m","        ","   ","4          ","    ","16.8 ","    ","13''-vF; pL; nBM; sev* invol at 100X with UHC          ","Often confused with NGC 2474; see Sky+Tel Apr 81 pg. 368                              "
// no catalog for VdB 66 found in "NGC 2149         ","VdB 66            ","BRTNB","MON","06 03.5","-09 44","99.9","99.9","271","11","   2   m","   1.3 m","   ","R          ","    ","     ","    ","F;*12 inv                                              ","                                                                                      "
// no catalog for Dark Doodad found in "Sa 149           ","Dark Doodad       ","DRKNB","MUS","12 25.0","-72 00","79.9","79.9","451","25"," 180   m","  12   m","   ","4 Ir       ","    ","     ","    ","easy in 8X42 binocs; curved dark lane within Musca     ","Just north of Gamma Mus;  loops toward GLOCL NGC 4833                                 "
// no catalog for Cannon 1-1 found in "PK 330+ 4.1      ","Cannon 1-1        ","PLNNB","NOR","15 51.3","-48 45","12.9","99.9","406","21","   1.0 s","        ","   ","1          ","    ","11.1 ","    ","                                                       ","                                                                                      "
// no catalog for Nassau 1 found in "PK  18+20.1      ","Nassau 1          ","PLNNB","OPH","17 12.9","-03 16","13.4","99.9","247","15","   5.0 s","        ","   ","           ","    ","16.6 ","    ","                                                       ","Stellar                                                                               "
// no catalog for The 3-26 found in "PK 358+ 3.8      ","The 3-26          ","PLNNB","OPH","17 31.2","-28 15","16.9","99.9","376","22","   6   s","        ","   ","           ","    ","16.5 ","    ","                                                       ","                                                                                      "
// no catalog for The 4-2 found in "PK   8+ 5.1      ","The 4-2           ","PLNNB","OPH","17 46.2","-18 40","16.5","99.9","338","15","  20   s","        ","   ","           ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for Cannon 3-1 found in "PK  38+12.1      ","Cannon 3-1        ","PLNNB","OPH","18 17.6","+10 09","12.4","7.9 ","204","15","   7   s","   5.5 s","   ","2          ","    ","12.5 ","    ","13''-vF; S; R; nBM; low surface brightness at 100X     ","Doubtful PLNNB                                                                        "
// no catalog for DG 79 found in "NGC 2067         ","DG 79             ","BRTNB","ORI","05 46.4","+00 06","99.9","99.9","226","11","   8   m","   3   m","   ","E          ","    ","     ","    ","F;pL;2068 s                                            ","                                                                                      "
// no catalog for Lund 1182 found in "NGC 2175S        ","Lund 1182         ","OPNCL","ORI","06 10.9","+20 36","99.9","99.9","137","5 ","  21   m","        ","   ","           ","20  ","     ","    ","                                                       ","                                                                                      "
// no catalog for Pegasus Dwarf found in "UGC 12613        ","Pegasus Dwarf     ","GALXY","PEG","23 28.6","+14 45","12.0","99.9","214","17","   4.6 m","   3   m","120","Ir+        ","    ","     ","    ","13''-F; pS; E 120; vlbM; Low Surface Brightness        ","dwarf Member Local Group                                                              "
// no catalog for Perseus I found in "Abell  426       ","Perseus I         ","GALCL","PER","03 19.7","+41 30","13.0","99.9","63 ","4 "," 190.4 m","        ","   ","2 0 II-III ","    ","     ","    ","36'' 81 galaxies counted in 2 deg; 17 pB               ","Centered on NGC 1275;Milky Way makes ID difficult; 88 galaxies                        "
// no catalog for AND II found in "AND II           ","PGC 4601          ","GALXY","PSC","01 16.4","+33 25","13.5","99.9","91 ","4 ","   2.0 m","   2.0 m","   ","dE2        ","    ","     ","    ","13''-eF;pL;nBM;irR;somewhat mottled at 100X            ","Andromeda Dwarf;Member Local Group                                                    "
// no catalog for Sculptor Dwarf found in "MCG -06-03-015   ","Sculptor Dwarf    ","GALXY","SCL","00 59.9","-33 43","10.5","17.1","351","18","  40   m","  31   m","110","E          ","    ","     ","    ","vvL;eeF;lE                                             ","ESO 351-G030;Member of Local Group;large and dim                                      "
// no catalog for Vd1-1 found in "PK 344+ 4.1      ","Vd1-1             ","PLNNB","SCO","16 42.6","-38 55","14.9","12.9","375","22","  10   s","        ","   ","           ","    ","16.7 ","    ","                                                       ","                                                                                      "
// no catalog for Cannon 1-3 found in "PK 345- 4.1      ","Cannon 1-3        ","PLNNB","SCO","17 26.3","-44 12","11.9","6.5 ","408","22","   5   s","        ","   ","1          ","    ","14.3 ","    ","                                                       ","                                                                                      "
// no catalog for Cannon 2-1 found in "PK 356- 4.1      ","Cannon 2-1        ","PLNNB","SCO","17 54.6","-34 23","13.9","99.9","377","22","   3   s","   2   s","   ","           ","    ","14   ","    ","13''-pB;vS;lE;central * seen at 220X                   ","On north side of M7 star cluster                                                      "
// no catalog for Archinal 1 found in "Archinal 1       ","                  ","OPNCL","SER","18 54.7","+05 33","99.9","99.9","250","16","   1.5 m","        ","   ","II 2 p     ","24  ","13.4 ","    ","                                                       ","Includes 4 GSC stars; near IC 4756                                                    "
// no catalog for YM 16 found in "PK  38+ 2.1      ","YM 16             ","PLNNB","SER","18 54.8","+06 02","14.2","99.9","205","16","   5.1 m","        ","   ","3b         ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for Sextans B dwarf found in "UGC  5373        ","Sextans B dwarf   ","GALXY","SEX","10 00.0","+05 20","11.3","14.3","234","13","   5.1 m","   3.5 m","110","Ir+        ","    ","     ","    ","13''-F;pL;E 2X1;nmBM at 100X                           ","dwarf irregular                                                                       "
// no catalog for Sextans A found in "UGCA  205        ","Sextans A         ","GALXY","SEX","10 11.0","-04 43","11.5","15  ","234","13","   5.9 m","   4.9 m","   ","Ir         ","    ","     ","    ","                                                       ","MCG -01-26-030                                                                        "
// no catalog for The 4-5 found in "PK   9+ 4.1      ","The 4-5           ","PLNNB","SGR","17 50.4","-19 03","16.2","99.9","338","15","   6.0 s","        ","   ","           ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for The 4-10 found in "PK  10+ 3.1      ","The 4-10          ","PLNNB","SGR","17 57.2","-18 06","16.8","99.9","339","15","  25   s","        ","   ","           ","    ","18.3 ","    ","                                                       ","                                                                                      "
// no catalog for SwSt 1 found in "PK   1- 6.2      ","SwSt 1            ","PLNNB","SGR","18 16.2","-30 52","11.8","6.5 ","377","22","   5   s","        ","   ","1          ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for Cannon 1-5 found in "PK   2- 9.1      ","Cannon 1-5        ","PLNNB","SGR","18 29.2","-31 30","12.6","7.2 ","378","22","   7.0 s","        ","   ","           ","    ","15.2 ","    ","                                                       ","                                                                                      "
// no catalog for DHW3 found in "PK  19-13.1      ","DHW3              ","PLNNB","SGR","19 17.1","-18 02","15.6","99.9","341","16","  34   s","  29   s","   ","           ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for DG 31 found in "NGC 1555         ","DG 31             ","BRTNB","TAU","04 21.9","+19 32","99.9","99.9","133","11","   0.5 m","        ","   ","R          ","    ","     ","    ","vF;S;variable;!!!                                      ","Hind's Variable Neb;associated with star T Tauri                                      "
// no catalog for Simeis 147 found in "Sh2-240          ","Simeis 147        ","SNREM","TAU","05 39.1","+28 00","99.9","99.9","97 ","5 "," 200   m"," 180   m","   ","E          ","    ","     ","    ","6''-eF;eL; low surface brightness filaments            ","Huge oval cloud w filaments;probably supernova remnant                                "
// no catalog for 0134+329 found in "3C  48           ","0134+329          ","QUASR","TRI","01 37.6","+33 09","16.5","99.9","91 ","4 ","        ","        ","   ","           ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for 47 Tucanae found in "NGC  104         ","47 Tucanae        ","GLOCL","TUC","00 24.1","-72 05"," 4.0","99.9","440","24","  30   m","        ","   ","III        ","    ","11.7 "," C  ","!! vB;vL;eRi;vmCM                                      ","X-ray source;* mags 11...;splendid cluster                                            "
// no catalog for Small Magellanc Cl found in "NGC  292         ","Small Magellanc Cl","GALXY","TUC","00 52.6","-72 48"," 2.3","14  ","460","24"," 319   m"," 205   m","45 ","Ir         ","    ","     ","    ","!!!vvB;eeL;iR;st 12...18                               ","Memb Local Group;LMC 22 deg distant                                                   "
// no catalog for Ursa Major I found in "Abell 1377       ","Ursa Major I      ","GALCL","UMA","11 47.1","+55 44","15.0","99.9","47 ","2 ","  20.2 m","        ","   ","1 3 III    ","    ","     ","    ","                                                       ","At limit of 16'';no NGC or IC members;* 6 mag superimp; 59 galaxies                   "
// no catalog for Ursa Minor Dwarf found in "UGC  9749        ","Ursa Minor Dwarf  ","GALXY","UMI","15 08.8","+67 12","10.9","17.8","28 ","2 ","  27.3 m","  16   m","70 ","dE6        ","    ","     ","    ","13''-vF;L;E 1.5X1 at 60X; low surface brghtnss         ","Member Local Group                                                                    "
// no catalog for Velghe 26 found in "PK 265- 2.1      ","Velghe 26         ","PLNNB","VEL","08 43.6","-46 08","17.5","99.9","397","20","   5   s","        ","   ","1          ","    ","     ","    ","                                                       ","                                                                                      "
// no catalog for Wild's triplet found in "Arp 248          ","Wild's triplet    ","GALXY","VIR","11 46.6","-03 52","13.3","99.9","237","13","   3   m","        ","   ","           ","    ","     ","    ","                                                       ","Tight Galaxy Group; A is 13.4 mag; B is 12.9 mag and C is 13.5 mag                    "
// no catalog for VCC 1203 found in "NGC 4471         ","VCC 1203          ","GALXY","VIR","12 29.6","+07 56","15.7","99.9","193","13","   0.3 m","   0.3 m","   ","Elliptical ","    ","     ","    ","vF;vS                                                  ","                                                                                      "
// no catalog for 2SZ 37 found in "NGC 5097         ","2SZ 37            ","GALXY","VIR","13 21.0","-12 28","15.0","99.9","285","14","   0.5 m","   0.3 m","45 ","Compact    ","    ","     ","    ","eF;eS;R;stell                                          ","                                                                                      "
// no catalog for SG  3.148 found in "NGC 6813         ","SG  3.148         ","BRTNB","VUL","19 40.4","+27 18","99.9","99.9","162","8 ","   3   m","        ","   ","E          ","    ","     ","    ","**in vf;S neb                                          ","                                                                                      "