using System.Collections.Generic;

namespace AstroLib.ObjectLibrary
{
    public class Constellations
    {
        public Dictionary<string, string> Lookup =
            new Dictionary<string, string>
                {
                    {"AND", "ANDROMEDA"},
                    {"ANT", "ANTLIA"},
                    {"APS", "APUS"},
                    {"AQR", "AQUARIUS"},
                    {"AQL", "AQUILA"},
                    {"ARA", "ARA"},
                    {"ARI", "ARIES"},
                    {"AUR", "AURIGA"},
                    {"BOO", "BOOTES"},
                    {"CAE", "CAELUM"},
                    {"CAM", "CAMELOPARDALIS"},
                    {"CNC", "CANCER"},
                    {"CVN", "CANES VENATICI"},
                    {"CMA", "CANIS MAJOR"},
                    {"CMI", "CANIS MINOR"},
                    {"CAP", "CAPRICORNUS"},
                    {"CAR", "CARINA"},
                    {"CAS", "CASSIOPEIA"},
                    {"CEN", "CENTAURUS"},
                    {"CEP", "CEPHEUS"},
                    {"CET", "CETUS"},
                    {"CHA", "CHAMAELEON"},
                    {"CIR", "CIRCINUS"},
                    {"COL", "COLUMBA"},
                    {"COM", "COMA BERENICES"},
                    {"CRA", "CORONA AUSTRALIS"},
                    {"CRB", "CORONA BOREALIS"},
                    {"CRV", "CORVUS"},
                    {"CRT", "CRATER"},
                    {"CRU", "CRUX"},
                    {"CYG", "CYGNUS"},
                    {"DEL", "DELPHINUS"},
                    {"DOR", "DORADO"},
                    {"DRA", "DRACO"},
                    {"EQU", "EQUULEUS"},
                    {"ERI", "ERIDANUS"},
                    {"FOR", "FORNAX"},
                    {"GEM", "GEMINI"},
                    {"GRU", "GRUS"},
                    {"HER", "HERCULES"},
                    {"HOR", "HOROLOGIUM"},
                    {"HYA", "HYDRA"},
                    {"HYI", "HYDRUS"},
                    {"IND", "INDUS"},
                    {"LAC", "LACERTA"},
                    {"LEO", "LEO"},
                    {"LMI", "LEO MINOR"},
                    {"LEP", "LEPUS"},
                    {"LIB", "LIBRA"},
                    {"LUP", "LUPUS"},
                    {"LYN", "LYNX"},
                    {"LYR", "LYRA"},
                    {"MEN", "MENSA"},
                    {"MIC", "MICROSCOPIUM"},
                    {"MON", "MONOCEROS"},
                    {"MUS", "MUSCA"},
                    {"NOR", "NORMA"},
                    {"OCT", "OCTANS"},
                    {"OPH", "OPHIUCHUS"},
                    {"ORI", "ORION"},
                    {"PAV", "PAVO"},
                    {"PEG", "PEGASUS"},
                    {"PER", "PERSEUS"},
                    {"PHE", "PHOENIX"},
                    {"PIC", "PICTOR"},
                    {"PSC", "PISCES"},
                    {"PSA", "PISCES AUSTRINUS"},
                    {"PUP", "PUPPIS"},
                    {"PYX", "PYXIS"},
                    {"RET", "RETICULUM"},
                    {"SGE", "SAGITTA"},
                    {"SGR", "SAGITTARIUS"},
                    {"SCO", "SCORPIUS"},
                    {"SCL", "SCULPTOR"},
                    {"SCT", "SCUTUM"},
                    {"SER", "SERPENS"},
                    {"SEX", "SEXTANS"},
                    {"TAU", "TAURUS"},
                    {"TEL", "TELESCOPIUM"},
                    {"TRA", "TRIANGULUM AUSTRALE"},
                    {"TRI", "TRIANGULUM"},
                    {"TUC", "TUCANA"},
                    {"UMA", "URSA MAJOR"},
                    {"UMI", "URSA MINOR"},
                    {"VEL", "VELA"},
                    {"VIR", "VIRGO"},
                    {"VOL", "VOLANS"},
                    {"VUL", "VULPECULA"},
                };
    }
}